In [70]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [72]:
df=pd.read_csv("C://Users/Meenakshi/dsbda/AirQuality.csv")

In [74]:
df

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,"2,6",1360,150,"11,9",1046,166,1056,113,1692,1268,"13,6","48,9","7,578"
1,10/03/2004,19.00.00,2,1292,112,"9,4",955,103,1174,92,1559,972,"13,3","47,7","7,255"
2,10/03/2004,20.00.00,"2,2",1402,88,"9,0",939,131,1140,114,1555,1074,"11,9","54,0","7,502"
3,10/03/2004,21.00.00,"2,2",1376,80,"9,2",948,172,1092,122,1584,1203,"11,0","60,0","7,867"
4,10/03/2004,22.00.00,"1,6",1272,51,"6,5",836,131,1205,116,1490,1110,"11,2","59,6","7,888"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,04/04/2005,10.00.00,"3,1",1314,-200,"13,5",1101,472,539,190,1374,1729,"21,9","29,3","7,568"
9353,04/04/2005,11.00.00,"2,4",1163,-200,"11,4",1027,353,604,179,1264,1269,"24,3","23,7","7,119"
9354,04/04/2005,12.00.00,"2,4",1142,-200,"12,4",1063,293,603,175,1241,1092,"26,9","18,3","6,406"
9355,04/04/2005,13.00.00,"2,1",1003,-200,"9,5",961,235,702,156,1041,770,"28,3","13,5","5,139"
9356,04/04/2005,14.00.00,"2,2",1071,-200,"11,9",1047,265,654,168,1129,816,"28,5","13,1","5,028"

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   object
 3   PT08.S1(CO)    9357 non-null   int64
 4   NMHC(GT)       9357 non-null   int64
 5   C6H6(GT)       9357 non-null   object
 6   PT08.S2(NMHC)  9357 non-null   int64
 7   NOx(GT)        9357 non-null   int64
 8   PT08.S3(NOx)   9357 non-null   int64
 9   NO2(GT)        9357 non-null   int64
 10  PT08.S4(NO2)   9357 non-null   int64
 11  PT08.S5(O3)    9357 non-null   int64
 12  T              9357 non-null   object
 13  RH             9357 non-null   object
 14  AH             9357 non-null   object
dtypes: int64(8), object(7)
memory usage: 1.1+ MB

In [78]:
df.describe()

,PT08.S1(CO),NMHC(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3)
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,1048.990061,-159.090093,894.595276,168.616971,794.990168,58.148873,1391.479641,975.072032
std,329.832710,139.789093,342.333252,257.433866,321.993552,126.940455,467.210125,456.938184
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
25%,921.000000,-200.000000,711.000000,50.000000,637.000000,53.000000,1185.000000,700.000000
50%,1053.000000,-200.000000,895.000000,141.000000,794.000000,96.000000,1446.000000,942.000000
75%,1221.000000,-200.000000,1105.000000,284.000000,960.000000,133.000000,1662.000000,1255.000000
max,2040.000000,1189.000000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000

In [80]:
df.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH'],
      dtype='object')

data Cleaning

In [84]:
df['CO(GT)'] = df['CO(GT)'].str.replace(',', '.').astype(float) #this is actually happening here '3,45'  â†’ replace(',', '.') â†’ '3.45' â†’ float â†’ 3.45
df['C6H6(GT)']=df['C6H6(GT)'].str.replace(',','.').astype(float)
df['T']=df['T'].str.replace(',','.').astype(float)
df['RH']=df['RH'].str.replace(',','.').astype(float)
df['AH']=df['AH'].str.replace(',','.').astype(float)

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   int64
 4   NMHC(GT)       9357 non-null   int64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   int64
 7   NOx(GT)        9357 non-null   int64
 8   PT08.S3(NOx)   9357 non-null   int64
 9   NO2(GT)        9357 non-null   int64
 10  PT08.S4(NO2)   9357 non-null   int64
 11  PT08.S5(O3)    9357 non-null   int64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: float64(5), int64(8), object(2)
memory usage: 1.1+ MB

In [89]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [91]:
df.drop(columns=['Date','Time'], inplace=True)

In [93]:
df

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,7.578
1,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,7.255
2,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,7.502
3,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,7.867
4,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,7.888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,3.1,1314,-200,13.5,1101,472,539,190,1374,1729,21.9,29.3,7.568
9353,2.4,1163,-200,11.4,1027,353,604,179,1264,1269,24.3,23.7,7.119
9354,2.4,1142,-200,12.4,1063,293,603,175,1241,1092,26.9,18.3,6.406
9355,2.1,1003,-200,9.5,961,235,702,156,1041,770,28.3,13.5,5.139
9356,2.2,1071,-200,11.9,1047,265,654,168,1129,816,28.5,13.1,5.028

data Integration

In [96]:
df=df.replace(-200,np.nan)

In [98]:
df.loc[9353]

CO(GT)              2.400
PT08.S1(CO)      1163.000
NMHC(GT)              NaN
C6H6(GT)           11.400
PT08.S2(NMHC)    1027.000
NOx(GT)           353.000
PT08.S3(NOx)      604.000
NO2(GT)           179.000
PT08.S4(NO2)     1264.000
PT08.S5(O3)      1269.000
T                  24.300
RH                 23.700
AH                  7.119
Name: 9353, dtype: float64

In [100]:
df.mean()

CO(GT)              2.152750
PT08.S1(CO)      1099.833166
NMHC(GT)          218.811816
C6H6(GT)           10.083105
PT08.S2(NMHC)     939.153376
NOx(GT)           246.896735
PT08.S3(NOx)      835.493605
NO2(GT)           113.091251
PT08.S4(NO2)     1456.264598
PT08.S5(O3)      1022.906128
T                  18.317829
RH                 49.234201
AH                 10.255303
dtype: float64

In [102]:
df.tail(10)

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
9347,0.5,888.0,NaN,1.3,528.0,77.0,1077.0,53.0,987.0,578.0,10.4,59.9,7.550
9348,1.1,1031.0,NaN,4.4,730.0,182.0,760.0,93.0,1129.0,905.0,9.5,63.1,7.531
9349,4.0,1384.0,NaN,17.4,1221.0,594.0,470.0,155.0,1600.0,1457.0,9.7,61.9,7.446
9350,5.0,1446.0,NaN,22.4,1362.0,586.0,415.0,174.0,1777.0,1705.0,13.5,48.9,7.553
9351,3.9,1297.0,NaN,13.6,1102.0,523.0,507.0,187.0,1375.0,1583.0,18.2,36.3,7.487
9352,3.1,1314.0,NaN,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,7.568
9353,2.4,1163.0,NaN,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,7.119
9354,2.4,1142.0,NaN,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,6.406
9355,2.1,1003.0,NaN,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,5.139
9356,2.2,1071.0,NaN,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,5.028

In [104]:
df=df.fillna(df.mean())

In [106]:
df.tail(10)

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
9347,0.5,888.0,218.811816,1.3,528.0,77.0,1077.0,53.0,987.0,578.0,10.4,59.9,7.550
9348,1.1,1031.0,218.811816,4.4,730.0,182.0,760.0,93.0,1129.0,905.0,9.5,63.1,7.531
9349,4.0,1384.0,218.811816,17.4,1221.0,594.0,470.0,155.0,1600.0,1457.0,9.7,61.9,7.446
9350,5.0,1446.0,218.811816,22.4,1362.0,586.0,415.0,174.0,1777.0,1705.0,13.5,48.9,7.553
9351,3.9,1297.0,218.811816,13.6,1102.0,523.0,507.0,187.0,1375.0,1583.0,18.2,36.3,7.487
9352,3.1,1314.0,218.811816,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,7.568
9353,2.4,1163.0,218.811816,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,7.119
9354,2.4,1142.0,218.811816,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,6.406
9355,2.1,1003.0,218.811816,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,5.139
9356,2.2,1071.0,218.811816,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,5.028

In [108]:
df.isnull().sum()

CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [110]:
df

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.000000,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,7.578
1,2.0,1292.0,112.000000,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,7.255
2,2.2,1402.0,88.000000,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,7.502
3,2.2,1376.0,80.000000,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,7.867
4,1.6,1272.0,51.000000,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,7.888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,3.1,1314.0,218.811816,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,7.568
9353,2.4,1163.0,218.811816,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,7.119
9354,2.4,1142.0,218.811816,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,6.406
9355,2.1,1003.0,218.811816,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,5.139
9356,2.2,1071.0,218.811816,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,5.028

In [112]:
df.drop_duplicates()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2.6,1360.0,150.000000,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,7.578
1,2.0,1292.0,112.000000,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,7.255
2,2.2,1402.0,88.000000,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,7.502
3,2.2,1376.0,80.000000,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,7.867
4,1.6,1272.0,51.000000,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,7.888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,3.1,1314.0,218.811816,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,7.568
9353,2.4,1163.0,218.811816,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,7.119
9354,2.4,1142.0,218.811816,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,6.406
9355,2.1,1003.0,218.811816,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,5.139
9356,2.2,1071.0,218.811816,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,5.028

In [124]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [126]:
target='AH'
X=df.drop(target,axis=1)
y=df[target]

In [131]:
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.2, random_state=42)

In [133]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)  # Works even if X has NaNs

LinearRegression()

In [135]:
y_pred=model.predict(X_test)

In [143]:
y_pred

array([12.21381171, 13.84078645,  9.02133641, ..., 15.46588727,
        7.60594993, 14.32429507])